# ---------------- #
# -  Ender Hunt  - #
# -  Config file - #
# -     Game     - #
# ---------------- #

#Hunter respawn time (second)
hunter-respawn-time: 120


# ---------------- #
# -  Ender Hunt  - #
# -  Config file - #
# -  Scoreboard  - #
# ---------------- #

# Placeholders:
# %hunters% Number of the hunters
# %hunters_name% List names of the hunters
# %speedrunner% name of the speedrunner

# Color Code: Â§
# https://minecraft.wiki/w/Formatting_codes

scoreboard:
  title: "Â§dç»ˆæœ« Â§eçŒäººæ¸¸æˆ"
  on-waiting:
    - "-----------------"
    - "IN TESTING VERSION"
    - "âŒš ç­‰å¾…æ¸¸æˆå¼€å¯..."
    - ""
    - "-----------------"
  on-running:
    - "-----------------"
    - "IN TESTING VERSION"
    - "â› é€Ÿé€šè€…: %speedrunner%"
    - "ğŸ¹ çŒäºº: %hunters%"
    - ""
    - "-----------------"
  on-ended:
    - "-----------------"
    - "IN TESTING VERSION"
    - "âŒš ç­‰å¾…æ¸¸æˆå¼€å¯..."
    - ""
    - "-----------------"